version: '3.7'
services:
  mkdocs-app:
    image: esame1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
    ports:
      - '80:80'
