version: '3.7'
services:
  mkdocs-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    #image: lupa2k2/gabrigay
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
    ports:
      - '80:80'
